import type { Metadata } from 'next'
import { BRAND, absoluteUrl, brandedTitle } from '@/lib/brand'
import { TrustPage, type TrustPageConfig } from '../trust-page'

export const metadata: Metadata = {
  title: 'AI Disclosure',
  description: `AI usage disclosure for ${BRAND.name} content collection, summarization, categorization, translation, and curation.`,
  alternates: { canonical: absoluteUrl('/ai-disclosure') },
  openGraph: {
    title: brandedTitle('AI Disclosure'),
    description: `How ${BRAND.name} uses AI for collection, summarization, categorization, and translation.`,
    url: absoluteUrl('/ai-disclosure'),
    images: [{ url: '/og-image.jpg', width: 1200, height: 630, alt: BRAND.name }],
  },
}

const config: TrustPageConfig = {
  label: 'AI Disclosure',
  title: `How ${BRAND.name} Uses AI`,
  description: `${BRAND.name} uses automated and AI-assisted workflows to process public source material into concise multilingual briefings.`,
  sections: [
    {
      title: 'AI-Generated Content',
      body: [
        'Summaries, classifications, translations, and the "Why Today Matters" analysis are generated by AI from the linked sources and published without human review. Every page, feed, and email that shows this text carries an AI-generated label.',
        'Found an error? Tell us through the contact page; corrections follow the corrections policy.',
      ],
    },
    {
      title: 'Where AI Is Used',
      bullets: [
        'Summarizing source material into concise briefing items.',
        'Classifying items by topic, category, and impact level.',
        'Translating summaries into supported languages.',
        'Formatting content for HTML pages, feeds, and Markdown summaries.',
      ],
    },
    {
      title: 'What AI Does Not Mean',
      body: [
        'AI assistance does not make a summary a primary source. The original publisher remains the best source for full context, quotes, legal details, financial numbers, and later updates.',
      ],
    },
    {
      title: 'Reader Guidance',
      body: [
        `Use ${BRAND.name} as a discovery and briefing layer. For high-stakes decisions, read the cited source and validate the facts independently.`,
      ],
    },
    {
      title: 'Search And AI Retrieval',
      body: [
        'The site exposes canonical HTML pages, Atom feeds, sitemap files, llms.txt, and Markdown summaries so search engines and AI retrieval systems can understand the content structure.',
      ],
    },
  ],
}

export default function AiDisclosurePage() {
  return <TrustPage config={config} />
}
