tech:
  - url: "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml"
    name: "The Verge AI"
  - url: "https://techcrunch.com/category/artificial-intelligence/feed/"
    name: "TechCrunch"
  - url: "https://venturebeat.com/feed"
    name: "VentureBeat"
  - url: "https://hnrss.org/newest?q=AI&points=50"
    name: "Hacker News"
  - url: "https://arstechnica.com/ai/feed/"
    name: "Ars Technica AI"
  - url: "https://www.wired.com/feed/tag/ai/latest/rss"
    name: "WIRED AI"
  - url: "https://the-decoder.com/feed/"
    name: "The Decoder"
  - url: "https://www.artificialintelligence-news.com/feed/rss/"
    name: "AI News"
  - url: "https://www.technologyreview.com/topic/artificial-intelligence/feed"
    name: "MIT Technology Review AI"
  - url: "https://huggingface.co/blog/feed.xml"
    name: "Hugging Face Blog"

investment:
  - url: "https://techcrunch.com/tag/funding/feed/"
    name: "TechCrunch Funding"
  - url: "https://news.crunchbase.com/feed/"
    name: "Crunchbase News"
  - url: "https://www.techmeme.com/feed.xml"
    name: "Techmeme"
  - url: "https://www.eu-startups.com/feed/"
    name: "EU-Startups"
  - url: "https://siliconangle.com/category/ai/feed"
    name: "SiliconANGLE"
  - url: "https://www.generational.pub/feed"
    name: "Generational"

tips:
  - url: "https://simonwillison.net/atom/everything/"
    name: "Simon Willison"
  - url: "https://www.reddit.com/r/ChatGPT/top/.rss?t=week"
    name: "Reddit r/ChatGPT"
  - url: "https://www.reddit.com/r/ClaudeAI/top/.rss?t=week"
    name: "Reddit r/ClaudeAI"
  - url: "https://www.reddit.com/r/PromptEngineering/top/.rss?t=week"
    name: "Reddit r/PromptEngineering"
  - url: "https://natesnewsletter.substack.com/feed"
    name: "Nate's Newsletter"
  - url: "https://lastweekin.ai/feed"
    name: "Last Week in AI"
